친구 관련 기능 구
klab-mtot/mtot-backend pull request #10
Opened 2023-05-21 07:41 UTC by GwonPyo

## 개요 🧾

## 변경사항 🛠

## 주의사항 ⚠

2023-05-21 10:49 UTC, LEE5J approved these changes

2023-05-21 12:55 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
> +    @Column(name = "fiendship_id")
`friendship_id` 오타 있습니다

2023-05-21 12:55 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
> +    @ManyToOne
`ManyToOne`에는 `fetchType.LAZY`를 붙여 주세요

2023-05-21 12:55 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
> +
이 경우에는 당사자의 허락 여부와 관계없이 친구가 맺어지는데, 친구를 맺었다는 변수가 있어야 할 것 같습니다
나아가서 친구 요청 / 수락에 대한 함수도 세분화해야할 것 같아요

2023-05-22 03:22 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
> +
오 놓친 부분이네요 감사합니다
수정해볼게용

2023-05-23 05:40 UTC, donghoony reviewed
일단 리뷰 하고 또 테스트 더 하고 올릴게요~

2023-05-23 05:40 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    @Transactional
상속받고 있는 JpaRepository에 이미 `@Transactional` 이 걸려 있어서 이 파일에서 따로 해줄 필요는 없습니다

2023-05-23 05:40 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    @Transactional
지우는 것이 나을까요 아니면 거절했다는 것을 따로 남겨두는 것이 좋을까요, delete 연산에 대한 overhead가 얼마나 되는지 모르겠어서 🤔

2023-05-23 05:40 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
>      Long id;
private을 붙여주세요~

2023-05-23 05:40 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipAcceptCheckRequest.java
> +public class FriendshipAcceptCheckRequest {
`FriendshipRequest`가 좀 더 명료하지 않은가요? 네이밍 이유가 궁금합니다

2023-05-23 05:40 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipUpdateRequest.java
> +    private String receiverEmail;
이 Request를 날릴 시점에는 `friendship_id`를 기반으로 수락/거절을 할 것 같은데 잘 모르겠습니다 🤔

2023-05-23 05:40 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +    private List<Member> findMemberIds(String requesterEmail, String receiverEmail) {
읽기 전용이니 `@Transactional(readonly = true)`가 낫겠네요

2023-05-23 05:40 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +        memberList.add(receiver.get());
Arraylist로 구현한 이유가 있나요?

2023-05-23 05:40 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +        int num;
조금 더 명료한 변수명을 사용해 주세요

2023-05-23 06:28 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    @Transactional
오 감사합니다

2023-05-23 06:29 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    @Transactional
흠 고민해 보긴 했는데 그럼 상태 표시를 차라리 0, 1, 2로 해서 할까? 그럼 안 지워도 될 것 같기도 하고

2023-05-23 06:29 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipAcceptCheckRequest.java
> +public class FriendshipAcceptCheckRequest {
아 이거 안 쓰는 거임 따로 지울게여

2023-05-23 06:30 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipUpdateRequest.java
> +    private String receiverEmail;
앱에서는 사용자가 수락을 누를 때 프론트에서 friendship_id를 바로 알 수 있는 방법이 없을거라고 생각해서 email을 두 개 넘겨주면 그거로 처리해야하지 않나 생각했습다
어떻게 하는 게 좋을까여

2023-05-23 06:31 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +    private List<Member> findMemberIds(String requesterEmail, String receiverEmail) {
오 알겠습니다

2023-05-23 06:32 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +        int num;
오게잉 바로 고치겠습다

2023-05-23 06:33 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +        memberList.add(receiver.get());
코드가 반복되는 것 같아서 그냥 함수로 requester와 receiver를 리턴해서 받아오고 싶었습니다.
근데 자바에서 리턴으로 두 개 받아오려면 List 타입으로 return해야 하는 것 같아서 List 안에 넣어주고 해당 List를 리턴하는 방식을 사용했습다

2023-05-24 15:56 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
>      @JoinColumn(name="requester_id", referencedColumnName = "member_id")
https://www.inflearn.com/questions/113969/joincolumn-%EC%9D%98-name-referencedcolumnname-%EC%97%90-%EB%8C%80%ED%95%B4-%EC%A7%88%EB%AC%B8-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4

`referencedColumnName`은 생략해도 됩니다

2023-05-25 21:50 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
>      @JoinColumn(name="requester_id", referencedColumnName = "member_id")
감사함다!

2023-05-25 21:51 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    @Transactional
해봤는데 테스트할 때 symbol찾을 수 없다는 에러 떠서 해당 부분은 수정에서 제외했습다

2023-05-26 17:24 UTC, donghoony requested changes
일단 추가 수정 요청사항을 올려요~

2023-05-26 17:24 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
> +    @Column(name = "accept", columnDefinition = "boolean default false")
여기에 boolean default false를 넣는것보다 아래 생성자로 만들어질 때 false를 넣는 방법은 어떨까요

2023-05-26 17:24 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
> +public class Friendship {
각 원소마다 줄 띄어주세요~

2023-05-26 17:24 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/dto/request/FriendshipUpdateRequest.java
> +    private String receiverEmail;
일단은 메일로 가시죠

2023-05-26 17:24 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    @Transactional
아 잘못 알고 있었네요
`@Query()` 어노테이션을 대신 사용해 주세요

2023-05-26 17:24 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    @Query("update Friendship f set f.accept=true where f.requester.id=:requesterId and f.receiver.id=:receiverId")
Hibernate에서는 Dirty checking을 사용하고 있어서, 업데이트를 하지 않아도 영속성 컨텍스트가 관리하는 것들에 대해서는 변경 감지 후 업데이트를 진행하므로 이 구문이 필요하지 않을 것 같아요.

2023-05-26 17:24 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/domain/Friendship.java
> +    private boolean accept;
`Boolean`형의 자료형의 네이밍은 `is~`로 하는 게 좋습니다. `isAccepted`는 어떨까요

2023-05-26 17:24 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +            updatedRows = friendshipRepository.updateAcceptTrue(requester.getId(), receiver.getId());
업데이트를 `repository`에서 진행하지 않고, 꺼낸 `friendship` 객체를 조작하면 Hibernate가 변경 감지 후 업데이트를 자동으로 진행합니다

2023-05-27 01:06 UTC, GwonPyo commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +            updatedRows = friendshipRepository.updateAcceptTrue(requester.getId(), receiver.getId());
넵! 모두 수정했습니당

2023-05-31 15:09 UTC, donghoony requested changes
거의 다 왔으니 화이팅~

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +        Member receiver = findMemberId(request.getReceiverEmail());
`Optional`의 함수들을 사용합시다!
지금 `develop` 브랜치랑 충돌이 안 나니까 그쪽거를 이쪽으로 머지해와서 Exception으로 하는 게 좋을 것 같네요
아래는 없으면 Throw하고, 있으면 가져오게끔 진행합니다. 편하죠~
```suggestion
        Member requester = memberRepository.findByEmail(request.getRequesterEmail())
                .orElseThrow(MemberNotFoundException::new);
        Member receiver = memberRepository.findByEmail(request.getReceiverEmail())
                .orElseThrow(MemberNotFoundException::new);
```

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +        Member user = findMemberId(request.getUserEmail());
이것도 위와 같이 바꾸면 좋을듯해요

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +        Member user = findMemberId(request.getUserEmail());
이것도~

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    List<Friendship> findUserFriendshipNotAccepted(Long userId);
메서드 이름이 아래와 좀 헷갈리는데, `findPendingFriendshipReceivedByMemberId`는 어떨까요

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    List<Friendship> findUserFriendshipNotAccept(Long userId);
이건 `findPendingFrendshipRequestedByMemberId`

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/repository/FriendshipRepository.java
> +    @Query("select f from Friendship f where f.receiver.id=:userId and f.isAccepted=false")
첫번째거랑 같은 쿼리에요

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +    public List<Friendship> checkUserRequestNotAccepted(FriendshipCheckRequest request){
User 대신 `Member`로 사용합시다~

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +    private void validateDuplicateFriendship(Member Requester, Member Receiver){
이부분도 Optional로 해결할 수 있으니 따로 만들지 않아도 될 듯합니다. 위쪽에 방법을 적어 둘게요

새로운 exception을 만들기는 해야하겠어요. `AlreadyFriendException`, `AlreadyPendingFriendRequestException`은 어떨까요

2023-05-31 15:09 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
>          validateFriendshipExist(requester, receiver);
자세한 내용은 아래에서 설명합니다
```suggestion
        friendshipRepository.findByRequesterIdAndReceiverId(requester.getId(), receiver.getId())
                        .ifPresent(friendship->{throw new AlreadyFriendException();});
```

2023-06-01 07:50 UTC, algoORgoal requested changes, later dismissed
1. 코멘트 변경
2. 테스트 추가
3. 메소드 이름 변경
에 대하여 리뷰하였습니다.

2023-06-01 07:50 UTC, algoORgoal commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +    public List<Friendship> checkMemberFriend(FriendCheckRequest request){
request를 받아서 `frinedshipList`를 반환하는 것이므로 `findFriendshipList`로 method 이름을 바꾸는게 이해하기 더 쉬운 것 같습니다.

2023-06-01 07:50 UTC, algoORgoal commented on src/main/java/org/konkuk/klab/mtot/service/FriendshipService.java
> +    public List<Friendship> checkMemberRequestNotAccepted(FriendshipCheckRequest request){
마찬가지로 `findFriendshipListNotAccepted`가 더 이해하기 편한 것 같습니다.

2023-06-01 07:50 UTC, algoORgoal commented on src/test/java/org/konkuk/klab/mtot/service/FriendServiceTest.java
> +        String mail = "abc@naver.com";
`//회원가입` 문구 추가하면 좋겠습니다.

2023-06-01 07:50 UTC, algoORgoal commented on src/test/java/org/konkuk/klab/mtot/service/FriendServiceTest.java
> +}
중복되는 친구 요청에 대한 확인도 필요합니다.

2023-06-01 07:50 UTC, algoORgoal commented on src/test/java/org/konkuk/klab/mtot/service/FriendServiceTest.java
> +        // 해당 요청 DB에서 삭제
`//삭제되었는 확인`이라고 커멘트 수정하면 좋겠습니다.

2023-06-01 07:50 UTC, algoORgoal commented on src/test/java/org/konkuk/klab/mtot/service/FriendServiceTest.java
> +        List<Friendship> checkList = friendshipService.checkMemberFriend(friendCheckRequest);
친구를 확인하기 위해서 checkList의 member variable이 정확한 값을 가지고 있는지 확인해햐 합니다.
List의 길이는 2인지, 이메일이 정확히 들어있는지 등등..

2023-06-01 13:36 UTC, donghoony commented
커밋에 SecretKey가 들어있어서 invalidate하고 새로 만들었어요, 커밋에서 해당 파일을 제거해 주세요~

2023-06-01 15:00 UTC, donghoony approved these changes

2023-06-01 15:01 UTC, merged