feat: JourneyController 추가
klab-mtot/mtot-backend pull request #23
Opened 2023-06-01 14:28 UTC by algoORgoal

## 개요 🧾

JourneyController에 필요한 최소한의 method를 추가하였습니다.

## 변경사항 🛠

email은 resolver를 통해 받아옵니다.
journeyName, teamId는 request body를 통해 받아옵니다.
생성된 journey의 id를 반환합니다.

## 주의사항 ⚠
Postman으로 아직 테스트가 진행되지 않았습니다.

2023-06-01 17:41 UTC, donghoony requested changes

2023-06-01 17:41 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/dto/request/CreateJourneyRequest.java
> +    private String journeyName;
`@NotNull` 어노테이션을 붙여 주세요

2023-06-02 04:23 UTC, LEE5J approved these changes

2023-06-02 11:36 UTC, donghoony approved these changes

2023-06-02 11:38 UTC, merged