팀(그룹) 멤버 가져오기 API 개발
klab-mtot/mtot-backend pull request #51
Opened 2023-06-05 21:54 UTC by GwonPyo

## 개요 🧾
팀(그룹) 멤버 가져오기 API 개발 

postman 확인 완료, test 통과 완료

![image](https://github.com/klab-mtot/mtot-backend/assets/85156021/5a627d8c-a71b-4b91-bc1e-075a2b08f8dc)

## 변경사항 🛠
팀(그룹) 멤버 가져오기 API 개발 →MemberTeamController 추가

## 주의사항 ⚠

2023-06-05 23:32 UTC, LEE5J approved these changes

2023-06-06 05:43 UTC, donghoony requested changes

2023-06-06 05:43 UTC, donghoony commented on src/main/java/org/konkuk/klab/mtot/service/MemberTeamService.java
> +        Team team = teamRepository.findById(teamId).orElseThrow(TeamNotFoundException::new);
`email`이 올바른 멤버인지 확인해주세요

2023-06-06 09:00 UTC, donghoony approved these changes

2023-06-06 09:01 UTC, merged